Repository EsupPortail/Esup-Pod, pull requests merged in 2024-03, with the labels that each got.

#1064 [DONE] Fix web-push-codelab.glitch.me link target in conf doc
  CONFIGURATION_FR.md
Labels: bug

#1063 [DONE] More 3.5.1 fixes
  pod/locale/fr/LC_MESSAGES/django.mo
  pod/locale/fr/LC_MESSAGES/django.po
  pod/locale/fr/LC_MESSAGES/djangojs.mo
  pod/locale/fr/LC_MESSAGES/djangojs.po
  pod/locale/nl/LC_MESSAGES/django.po
  pod/locale/nl/LC_MESSAGES/djangojs.po
  pod/main/static/css/pod.css
  pod/main/static/js/infinite.js
  pod/settings.py
  pod/video/forms.py
  pod/video/management/commands/migrate_bbb_recordings.py
  pod/video/models.py
  pod/video/templates/videos/link_video.html
  pod/video/templates/videos/video-script.html
  pod/video/templates/videos/video_access_tokens.html
  pod/video/templates/videos/video_edit.html
  pod/video/templates/videos/video_list_table_selectable.html
  pod/video/templates/videos/video_row_select.html
  pod/video/tests/test_obsolescence.py
Labels: bug, enhancement

#1076 [DONE] do not fail on HTTP requests with numerous/long cookies
  pod_uwsgi.ini
Labels: bug

#1078 [DONE] Fix dressing and cutting and add unit tests 3.5.2
  pod/completion/models.py
  pod/completion/tests/test_models.py
  pod/cut/context_processors.py
  pod/cut/forms.py
  pod/cut/models.py
  pod/cut/templates/video_cut.html
  pod/cut/tests/test_models.py
  pod/cut/tests/test_views.py
  pod/cut/urls.py
  pod/cut/views.py
  pod/dressing/context_processors.py
  pod/dressing/models.py
  pod/dressing/templates/video_dressing.html
  pod/dressing/tests/test_models.py
  pod/dressing/tests/test_views.py
  pod/dressing/views.py
  pod/enrichment/models.py
  pod/enrichment/tests/test_models.py
  pod/main/configuration.json
  pod/main/rest_router.py
  pod/main/settings.py
  pod/main/static/js/main.js
  pod/main/static/video_test/video_test_encodage_transcription.mp4
  pod/main/templates/navbar.html
  pod/main/test_settings.py
  pod/playlist/tests/test_views.py
  pod/podfile/static/podfile/js/filewidget.js
  pod/recorder/plugins/type_studio.py
  pod/settings.py
  pod/urls.py
  pod/video/forms.py
  pod/video/templates/videos/dashboard.html
  pod/video/templates/videos/link_video.html
  pod/video/templates/videos/video_access_tokens.html
  pod/video/templates/videos/video_row_select.html
  pod/video/urls.py
  pod/video_encode_transcript/Encoding_video.py
  pod/video_encode_transcript/encode.py
  pod/video_encode_transcript/encoding_studio.py
  pod/video_encode_transcript/encoding_tasks.py
  pod/video_encode_transcript/rest_views.py
  pod/video_encode_transcript/tests/test_remote_encode_transcode.py
  pod/video_encode_transcript/tests/testimage.jpg
Labels: bug

#1084 [Done] Improve keyboard nav
  pod/main/static/css/pod.css
  pod/main/templates/base.html
Labels: enhancement

#1086 [DONE] Fix the auto fill video password field
  pod/video/forms.py
Labels: bug, enhancement
